variable "region_name" {}
variable "access_key" {}
variable "secret_key" {}
variable "vpc_name" {}
variable "vpc_cidr" {}
variable "subnet_name1" {}
variable "subnet_cidr1" {}
variable "subnet_name2" {}
variable "subnet_cidr2" {}
variable "subnet_name3" {}
variable "subnet_cidr3" {}
variable "internet_gateway_name" {}
variable "route_table_name" {}
variable "security_group_name" {}
variable "ami_id" {}
variable "instance_type" {}
variable "pem_key_name" {}
variable "instance_name" {}